# Generated by Django 2.1 on 2019-11-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Highway_to_hell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('start_point', models.CharField(max_length=30)),
                ('finish_point', models.CharField(max_length=30)),
            ],
        ),
    ]
