# Generated by Django 2.1 on 2019-09-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_auto_20190604_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdate', models.DateTimeField(null=True)),
                ('zcharge', models.CharField(max_length=100, null=True)),
                ('zprowe', models.FloatField(null=True)),
                ('zbadwe', models.FloatField(null=True)),
            ],
        ),
    ]
