# Generated by Django 2.1 on 2019-12-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_casttest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Twitter2010',
        ),
    ]
